# Generated by Django 3.1.3 on 2021-08-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_category', models.CharField(default='', max_length=50)),
                ('about_desc', models.TextField()),
                ('about_image', models.ImageField(default='', upload_to='images/about')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='', max_length=50)),
                ('course_category', models.CharField(default='', max_length=50)),
                ('course_desc', models.TextField()),
                ('course_chapter', models.TextField()),
                ('course_duration', models.CharField(default='', max_length=50)),
                ('course_image', models.ImageField(default='', upload_to='images/courses')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(default='', max_length=50)),
                ('gallery_cat', models.CharField(choices=[('all', 'ALL'), ('lab', 'LAB'), ('classroom', 'CLASSROOM'), ('students', 'STUDENTS'), ('other', 'OTHER')], default='all', max_length=20)),
                ('gallery_image', models.ImageField(default='', upload_to='images/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='', max_length=50)),
                ('course_desc', models.TextField()),
                ('course_icon', models.ImageField(default='', upload_to='images/premiumcoursesicon')),
            ],
        ),
        migrations.CreateModel(
            name='relatedCourses',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False)),
                ('rc_name', models.CharField(default='', max_length=50)),
                ('rc_description', models.CharField(default='', max_length=140)),
                ('rc_category', models.CharField(default='', max_length=50)),
                ('rc_duration', models.CharField(default='', max_length=50)),
                ('rc_image', models.ImageField(default='', upload_to='images/relatesdcourses')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaxproApp.courseoffered')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumCourseEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('select', 'SELECT'), ('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], default='Select', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('premium_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaxproApp.premiumcourse')),
            ],
        ),
    ]
